graph_config:
   only_hits: true
   k: 40
   tracking: true

custom_model_kwargs:
   # add custom model kwargs here
   n_postgn_dense_blocks: 4
   clust_space_norm: none


#treename:
selection:
   ### use `&`, `|`, `~` for logical operations on numpy arrays
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7!=0)
   #(recojet_e>=5)

test_time_selection:
   ### selection to apply at test time (i.e., when running w/ --predict)
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7==0)
   #(recojet_e<5)

new_variables:
   ### [format] name: formula
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_etarel)
   #sv_mask: awkward.JaggedArray.ones_like(sv_etarel)
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_e)
   hit_mask: ak.ones_like(hit_EDep)
   part_mask: ak.ones_like(part_p)

preprocess:
  ### method: [manual, auto] - whether to use manually specified parameters for variable standardization
  ### [note]: `[var]_mask` will not be transformed even if `method=auto`
  method: auto
  ### data_fraction: fraction of events to use when calculating the mean/scale for the standardization
  data_fraction: 0.1

inputs:
   pf_points:
      pad_mode: wrap
      length: 25000
      vars:
         - [hit_x, null]
         - [hit_y, null]
         - [hit_z, null]
   pf_features:
      pad_mode: wrap
      length: 25000
      vars:
         - [hit_x, null] #VX
         - [hit_y, null] #VX
         - [hit_z, null] #VX
         - [hit_EDep, null] # VX DC
         - [superLayer, null] # DC
         - [layer, null] # DC
         - [phi, null] #  DC
         - [distance_to_wire, null] # DC
         - [z_position_along_wire, null] # DC
         - [hit_type, null] # VX DC
         #- [cluster_count, null] # DC

   pf_vectors:
      length: 25000
      pad_mode: wrap
      vars:
         - [part_theta, null]  #2
         - [part_phi, null] #3
         - [part_m, null] #4
         - [part_pid, null]  #15
         - [part_id, null]  #6
   pf_vectoronly:
      length: 25000
      pad_mode: wrap
      vars:
      - [hit_genlink0, null] #2



   pf_mask:
      length: 25000
      pad_mode: constant
      vars:
         - [hit_mask, null]
         - [part_mask, null]


labels:
   ### type can be `simple`, `custom`
  ### [option 1] use `simple` for binary/multi-class classification, then `value` is a list of 0-1 labels
   #type: simple
   #value: [
   #   hit_ty
   #   ]
   ### [option 2] otherwise use `custom` to define the label, then `value` is a map
   # type: custom
   # value:
      # target_mass: np.where(fj_isQCD, fj_genjet_sdmass, fj_gen_mass)

observers:
   #- recojet_e
   #- recojet_theta
   #- recojet_phi
   #- recojet_m
   #- n_pfcand

